"""Constants for QuestDrive Syncer."""

VIDEO_SHOTS_PATH = "list/storage/emulated/0/Oculus/VideoShots/"
FAILURE_EXIT_CODE = 3
ACTIVELY_RECORDING_EXIT_CODE = 4
TOO_MUCH_SPACE_EXIT_CODE = 5
NOT_ENOUGH_BATTERY_EXIT_CODE = 6
QUESTDRIVE_POLL_RATE_MINUTES = 5
