---
fail_fast: true

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-toml
          - id: check-yaml
          - id: check-ast
          - id: check-merge-conflict
          - id: check-added-large-files
          - id: check-case-conflict
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.21.0
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt
    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: 129dd8a
      hooks:
          - id: pretty-format-toml
            args: [--autofix]
    - repo: https://gitlab.com/smop/pre-commit-hooks
      rev: df034f88cf92b394e6f00a78fa97a2aa4e270e60
      hooks:
          - id: check-poetry
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.1.9
      hooks:
          - id: ruff
            args:
                - --select
                - ALL
                - --ignore
                - DTZ001,DTZ005,DTZ007,S101,E501,T201,D213,D203,ARG001,PLR0913
                - --fix
          - id: ruff-format
    - repo: local
      hooks:
          - id: mypy
            name: Check types
            description: This hook runs MyPy with strict settings
            entry: poetry
            language: system
            types: [python]
            args:
                - run
                - mypy
                - --strict
                - .
            pass_filenames: false
          - id: pytest
            name: Check passing tests & TypeGuard usage
            description: This hook runs PyTest with TypeGuard & coverage enabled
            entry: poetry
            language: system
            types: [python]
            args:
                - run
                - pytest
            pass_filenames: false
          - id: coverage
            name: Check coverage
            description: Ensure all code is covered
            entry: coverage
            language: system
            args:
                - report
                - --fail-under=100
            types: [python]
            pass_filenames: false
          - id: version-bumped
            name: Version Bumped
            description: Ensure version has been bumped
            entry: poetry
            language: system
            types: [python]
            args:
                - run
                - python
                - hooks/version_bumped.py
            pass_filenames: false
